vim.keymap.set("n", "-", "<cmd>Oil<CR>", { desc = "Open oil" })
vim.keymap.set("n", "<leader>ff", "<cmd>Telescope find_files<CR>", { desc = "Telescope find files" })
vim.keymap.set("n", "<leader>fw", "<cmd>Telescope live_grep<CR>", { desc = "Telescope live grep" })
vim.keymap.set("n", "<leader>fs", "<cmd>Telescope symbol_grep<CR>", { desc = "Telescope symbol grep" })
vim.keymap.set("n", "<leader>fb", "<cmd>Telescope symbol_grep<CR>", { desc = "Telescope buffers" })
vim.keymap.set("n", "<leader>fh", "<cmd>Telescope help_tags<CR>", { desc = "Telescope help tags" })
